spring.data.mongodb.database=${DOCUMENTDB_DATABASE}
spring.data.mongodb.uri=${DOCUMENTDB_URI}
spring.data.mongodb.username=${DOCUMENTDB_USERNAME}
spring.data.mongodb.password=${DOCUMENTDB_PASSWORD}
vector-store.file=/spring-chatgpt-sample-webapi/private-data/vector_store.json



